# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrainDaily' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TrainDaily

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'TrainDailyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TrainDaily-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TrainDaily-tvOS

  target 'TrainDaily-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
